In [1]:
#install python package:numpy

In [2]:
#this is a cell 

In [3]:
#pip install numpy (one time activity)

In [4]:
import numpy as np

In [5]:
myList = [9,8,7,6]
f = ["red","yellow"]

In [6]:
print(myList)
print(f)

[9, 8, 7, 6]
['red', 'yellow']


In [7]:
type(myList) #object type

list

In [8]:
# dir(np) show all the inbuilt function

In [9]:
# help(np) 

In [10]:
np.array(myList)

array([9, 8, 7, 6])

In [11]:
arr = np.array(myList)

In [12]:
arr.size
arr.shape

(4,)

In [13]:
print(arr)
print(type(arr))

[9 8 7 6]
<class 'numpy.ndarray'>


In [14]:
arr

array([9, 8, 7, 6])

In [15]:
mylist1=[1,2,3,4]
mylist2=[5,6,7,8]
mylist3=[9,10,11,12]

In [16]:
ar = np.array([mylist1,mylist2,mylist3])

In [17]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
type(ar)

numpy.ndarray

In [19]:
ar.shape

(3, 4)

In [20]:
ar.size


12

In [21]:
mylist1=[1,2,3,4]

In [22]:
ar = np.array(mylist1)

In [23]:
print(ar[0]) #index value

1


In [24]:
print(ar[1])

2


In [25]:
print("3rd elements is::",ar[2] and "4th element is::",ar[3])

3rd elements is:: 4th element is:: 4


In [26]:
mylist1=[1,2,3,4]
mylist2=[5,6,7,8]
mylist3=[9,10,11,12]
ar = np.array([mylist1,mylist2,mylist3])

In [27]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
ar[1,2]

7

In [29]:
mylist1=[1,2,3,4,15]
mylist2=[5,6,7,8,16]
mylist3=[9,10,11,12,17]
ar = np.array([mylist1,mylist2,mylist3])

In [30]:
ar

array([[ 1,  2,  3,  4, 15],
       [ 5,  6,  7,  8, 16],
       [ 9, 10, 11, 12, 17]])

In [31]:
ar[1,3]


8

In [32]:
ar[1,4]

16

In [33]:
ar[0,0]

1

In [34]:
ar[1,2]

7

In [35]:
ar.shape

(3, 5)

In [36]:
print(ar)
print("shape::",ar.shape)
print("size::",ar.size)
#indexing using both row and column
print("indexing value::",ar[0,0])
print("indexing value::",ar[1,1])

[[ 1  2  3  4 15]
 [ 5  6  7  8 16]
 [ 9 10 11 12 17]]
shape:: (3, 5)
size:: 15
indexing value:: 1
indexing value:: 6


In [37]:
newarr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])

In [38]:
print(newarr)
print("shape::",newarr.shape)
print("size::",newarr.size)
print("indexing value::",newarr[0,0])
print("indexing value::",newarr[1,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]
shape:: (5, 5)
size:: 25
indexing value:: 1
indexing value:: 7


In [39]:
#negative indexing
print(newarr[3,-3])

13


In [40]:
mylt=[1, 2, 3, 4, 5, 6, 7, 8]

In [41]:
mylt  #SLICING ONE D

[1, 2, 3, 4, 5, 6, 7, 8]

In [42]:
AR=np.array(mylt)

In [43]:
AR

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
print(AR[0:5])
print(AR[3:])
print(AR[1:4:2])

[1 2 3 4 5]
[4 5 6 7 8]
[2 4]


In [45]:
print(AR[0:4])

[1 2 3 4]


In [46]:
#negative slicing:
print(AR[-3:-1])
print(AR[:-1])

[6 7]
[1 2 3 4 5 6 7]


In [47]:
#Use the step value to determine the step of the slicing:
print(AR[::6])
print(AR[:5:2])

[1 7]
[1 3 5]


In [48]:
#2d array slicing::
my_lst1=[1,2,3,4,5]
my_lst2=[6,7,8,9,10]
my_lst3=[11,12,13,14,15]

arr=np.array([my_lst1,my_lst2,my_lst3])
print(arr[1, 1:4])

[7 8 9]


In [49]:
print(arr[0:2,2])
print(arr[0:3,1])

[3 8]
[ 2  7 12]


In [50]:
print(arr[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [51]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [52]:
print(arr[1:,:2])

[[ 6  7]
 [11 12]]


In [53]:
print(arr[:,3:])

[[ 4  5]
 [ 9 10]
 [14 15]]


In [54]:
silArr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [55]:
print(silArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
silArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
silArr[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [58]:
print(silArr[0, 1])

2


In [59]:
#ARANGE FUNCTION::
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
#10-20
np.arange(10,20+1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [61]:
#10-20-2
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [62]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [64]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype="S") #forcing the system to do
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [65]:
#LINSPACE::
np.linspace(0,100,num=5)

array([  0.,  25.,  50.,  75., 100.])

In [66]:
#DATA TYPE::
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [67]:
arr=np.array(["apple","ora"])
print(arr.dtype)

<U5


In [68]:
arr=np.array([1.2j])
print(arr.dtype)

complex128


In [69]:
arr=np.array([1,2,3,4,5],dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [70]:
arr=np.array([1.0j,1.7])
print(arr.dtype)

complex128


In [71]:
arr=np.array([2.0])
print(arr.dtype)

float64


In [72]:
arr=np.array([1,2,3,4,5])

print(arr.dtype)

int64


In [73]:
#Array Math
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [74]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [75]:
x+y

array([[ 6,  8],
       [10, 12]])

In [76]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [77]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [78]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [79]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [80]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [81]:
x.shape

(2, 2)

In [82]:
y.shape

(2, 2)

In [83]:
x+y


array([[ 6,  8],
       [10, 12]])

In [84]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8],[1,4]])

In [85]:
np.add(x,y) # rows and clounm is not equal

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
x.shape
y.shape

In [ ]:
np.exp(x)  #exponent

In [ ]:
np.log(y) #logaritham

In [ ]:
np.cos(x) #cos

In [ ]:
np.tan(x) #tan

In [ ]:
#floor ,ceil,round

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2,3] ,[4,5,6] ,[7,8,9]])

In [ ]:
print(A)

In [ ]:
print(A[0:3,2])

In [ ]:
print(A[0:3,1])

In [ ]:
print(A[2,2])

In [ ]:
b = np.array([[1,2,3,4,5,67,9]])

In [ ]:
print(b)

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6],[2,3,4]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [ ]:
print(c.ndim)

In [ ]:
print(a.dtype)

In [ ]:
np.arange(100,200)

In [ ]:
np.arange(100,200,11)

In [ ]:
v = np.array([[1,2],[3,4]], dtype=np.float64)
m = np.array([[6,7],[8,9]], dtype=np.float64)    # dtypen is optional 

In [ ]:
print(v)
print(m)

In [ ]:
np.add(v,m)

In [ ]:
np.subtract(v,m)

In [ ]:
np.multiply(v,m)

In [ ]:
np.divide(v,m)

In [ ]:
v/m

In [ ]:
v+m

In [ ]:
v-m

In [ ]:
print(v)

In [ ]:
v.T

In [ ]:
np.exp(v)

In [ ]:
np.cos(m)

In [ ]:
#EXAMPLES

#Original array: 
#[ 3.1  3.5  4.5  2.9 -3.1 -3.5 -5.9]

#around:    [ 3.  4.  4.  3. -3. -4. -6.]
#floor:     [ 3.  3.  4.  2. -4. -4. -6.]
#ceil:      [ 4.  4.  5.  3. -3. -3. -5.]
#trunc:     [ 3.  3.  4.  2. -3. -3. -5.]
#round:     [3.0, 4.0, 4.0, 3.0, -3.0, -4.0, -6.0]


In [ ]:
# COPY ARRAY

In [ ]:
arr=np.array([1,2,3,4,5])
x = arr

In [ ]:
x

In [ ]:
print(x)

In [ ]:
arr[0]

In [ ]:
arr[1] = 100 #replace

In [ ]:
print(arr)

In [ ]:
x

In [ ]:
x[3]=200

In [ ]:
print(x)

In [ ]:
# COPY::

y=np.array([6,7,8,9,1])
X=y.copy()


In [ ]:
print(y)

In [ ]:
y[1]=10

In [ ]:
print(y)

In [ ]:
print(X)

In [ ]:
#VIEW::

a=np.array([1,2,3,4])
x=a.view()
a[0]=1888

print(a)
print(x)

In [ ]:
#RESHAPING::

In [ ]:
b=np.arange(1,21)
new=b.reshape(5,4)

In [ ]:
print(new) #1d covert to 2d

In [ ]:
#convert 2d TO 1d flatterring dimension

In [ ]:
new.reshape(-1)

In [ ]:
##### Iterating Arrays

#Iterating means going through elements one by one.

#As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

#If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
#example 1 line::
np.arange(1,7).reshape(3,2).sum(axis=0)

In [ ]:
arr=np.arange(1,9).reshape(4,2)

In [ ]:
arr

In [ ]:
for i in arr:
    print(i)

In [94]:
#CONCATENATE ARRAY::

[1 2 3 6 7 8]


In [98]:
arr1 = np.array([1,2,3])
arr2 = np.array([6,7,8])

k = np.concatenate((arr1,arr2))
                     
print(k)

[1 2 3 6 7 8]


In [102]:
#Join two 2-D arrays along rows (axis=0):
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
##### NumPy Splitting Array

In [105]:
#If the array has less elements than required, it will adjust from the end accordingly.

arr=np.array([1,2,3,4,5,6,7])
new=np.array_split(arr,4)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]


In [106]:
# Split the 2-D array into three 2-D arrays::

arr=np.array([[1,2],[11,23],[4,5],[7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[ 1,  2],
       [11, 23]]), array([[4, 5],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [107]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [108]:
#Split the 2-D array into three 2-D arrays along rows.::

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
