In [1]:
#install python package:numpy

In [2]:
#this is a cell 

In [3]:
#pip install numpy  {one time activity}

In [4]:
import numpy as np

In [5]:
myList = [9,8,7,6]
f = ["red","yellow"]

In [6]:
print(myList)
print(f)

[9, 8, 7, 6]
['red', 'yellow']


In [7]:
type(myList) #object type

list

In [8]:
# dir(np) show all the inbuilt function

In [9]:
# help(np) 

In [10]:
np.array(myList)

array([9, 8, 7, 6])

In [11]:
arr = np.array(myList)

In [12]:
arr.size
arr.shape

(4,)

In [13]:
print(arr)
print(type(arr))

[9 8 7 6]
<class 'numpy.ndarray'>


In [14]:
arr

array([9, 8, 7, 6])

In [15]:
mylist1=[1,2,3,4]
mylist2=[5,6,7,8]
mylist3=[9,10,11,12]

In [16]:
ar = np.array([mylist1,mylist2,mylist3])

In [17]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
type(ar)

numpy.ndarray

In [19]:
ar.shape

(3, 4)

In [20]:
ar.size


12

In [21]:
mylist1=[1,2,3,4]

In [22]:
ar = np.array(mylist1)

In [23]:
print(ar[0]) #index value

1


In [24]:
print(ar[1])

2


In [25]:
print("3rd elements is::",ar[2] and "4th element is::",ar[3])

3rd elements is:: 4th element is:: 4


In [26]:
mylist1=[1,2,3,4]
mylist2=[5,6,7,8]
mylist3=[9,10,11,12]
ar = np.array([mylist1,mylist2,mylist3])

In [27]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
ar[1,2]

7

In [29]:
mylist1=[1,2,3,4,15]
mylist2=[5,6,7,8,16]
mylist3=[9,10,11,12,17]
ar = np.array([mylist1,mylist2,mylist3])

In [30]:
ar

array([[ 1,  2,  3,  4, 15],
       [ 5,  6,  7,  8, 16],
       [ 9, 10, 11, 12, 17]])

In [31]:
ar[1,3]


8

In [32]:
ar[1,4]

16

In [33]:
ar[0,0]

1

In [34]:
ar[1,2]

7

In [35]:
ar.shape

(3, 5)

In [36]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype="S") #forcing the 
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [37]:
arr=np.array([1,2,3,4,5],dtype=np.int64)
print(arr.dtype)

int64


In [38]:
arr

array([1, 2, 3, 4, 5])

In [39]:
arr=np.array([1,2,3,4,5],dtype=np.float64)
print(arr.dtype)

float64


In [40]:
arr

array([1., 2., 3., 4., 5.])

In [41]:
#Array Math
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [42]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [43]:
x+y

array([[ 6,  8],
       [10, 12]])

In [44]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [45]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [46]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [47]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [48]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [49]:
x.shape

(2, 2)

In [50]:
y.shape

(2, 2)

In [51]:
x+y


array([[ 6,  8],
       [10, 12]])

In [52]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8],[1,4]])

In [53]:
np.add(x,y) # rows and clounm is not equal

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
x.shape
y.shape

In [ ]:
np.exp(x)  #exponent

In [ ]:
np.log(y) #logaritham

In [ ]:
np.cos(x) #cos

In [ ]:
np.tan(x) #tan

In [ ]:
#floor ,ceil,round
x=np.array([[1.5,2.5],[3.9,4.9]],dtype=np.float64)

In [ ]:
print(x)

In [ ]:
np.floor(x)

In [ ]:
np.ceil(x)

In [ ]:
np.round(x)

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.array([[9,2],[3,7]])

In [ ]:
np.dot(x,y)

In [ ]:
x*y*z

In [ ]:
total = np.multiply(x,y) #it will multiply only x and y ,only 1st and 2nd parameters are considered in numpy so 

In [ ]:
total

In [ ]:
total * z

In [ ]:
import numpy as np
a = np.array([1,2])
b = np.array([1,3])


In [ ]:
a.dot(b) #confusion

In [ ]:
#row wise sum 1=row , 0=column

In [54]:
xi=np.array([[1,2,3],[5,6,7],[8,9,1]])

In [56]:
xi

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 1]])

In [55]:
np.sum(xi)

42

In [57]:
xi

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 1]])

In [60]:
np.sum(xi,axis=0)

array([14, 17, 11])

In [59]:
xi.T #transpose

array([[1, 5, 8],
       [2, 6, 9],
       [3, 7, 1]])

In [61]:
xi.T.T

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 1]])

In [62]:
#VIEW::

a=np.array([1,2,3,4])
x=a.view()
a[0]=1888

print(a)
print(x)

[1888    2    3    4]
[1888    2    3    4]
